/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as AdmissionsApplyRouteImport } from './routes/admissions.apply'
import { Route as AdmissionsStatusRouteImport } from './routes/admissions.status'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAssignmentsRouteImport } from './routes/portal.assignments'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalQuizzesRouteImport } from './routes/portal.quizzes'
import { Route as PortalRegisterRouteImport } from './routes/portal.register'
import { Route as PortalResourcesRouteImport } from './routes/portal.resources'
import { Route as PortalResultsRouteImport } from './routes/portal.results'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as UpdatesAcademicRouteImport } from './routes/updates.academic'
import { Route as UpdatesOfficialRouteImport } from './routes/updates.official'
import { Route as UpdatesTeacherJobsRouteImport } from './routes/updates.teacher-jobs'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesIdRouteImport } from './routes/admin.courses.$id'
import { Route as PortalCoursesIndexRouteImport } from './routes/portal.courses.index'
import { Route as PortalCoursesSlugRouteImport } from './routes/portal.courses.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplyRoute = AdmissionsApplyRouteImport.update({
  id: '/admissions/apply',
  path: '/admissions/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsStatusRoute = AdmissionsStatusRouteImport.update({
  id: '/admissions/status',
  path: '/admissions/status',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAssignmentsRoute = PortalAssignmentsRouteImport.update({
  id: '/portal/assignments',
  path: '/portal/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQuizzesRoute = PortalQuizzesRouteImport.update({
  id: '/portal/quizzes',
  path: '/portal/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/portal/register',
  path: '/portal/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResourcesRoute = PortalResourcesRouteImport.update({
  id: '/portal/resources',
  path: '/portal/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResultsRoute = PortalResultsRouteImport.update({
  id: '/portal/results',
  path: '/portal/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesAcademicRoute = UpdatesAcademicRouteImport.update({
  id: '/updates/academic',
  path: '/updates/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesOfficialRoute = UpdatesOfficialRouteImport.update({
  id: '/updates/official',
  path: '/updates/official',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesTeacherJobsRoute = UpdatesTeacherJobsRouteImport.update({
  id: '/updates/teacher-jobs',
  path: '/updates/teacher-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const PortalCoursesIndexRoute = PortalCoursesIndexRouteImport.update({
  id: '/portal/courses/',
  path: '/portal/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCoursesSlugRoute = PortalCoursesSlugRouteImport.update({
  id: '/portal/courses/$slug',
  path: '/portal/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/quizzes': typeof PortalQuizzesRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/results': typeof PortalResultsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/updates/academic': typeof UpdatesAcademicRoute
  '/updates/official': typeof UpdatesOfficialRoute
  '/updates/teacher-jobs': typeof UpdatesTeacherJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/portal/courses/$slug': typeof PortalCoursesSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/portal/courses/': typeof PortalCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/quizzes': typeof PortalQuizzesRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/results': typeof PortalResultsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/updates/academic': typeof UpdatesAcademicRoute
  '/updates/official': typeof UpdatesOfficialRoute
  '/updates/teacher-jobs': typeof UpdatesTeacherJobsRoute
  '/admin': typeof AdminIndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/portal/courses/$slug': typeof PortalCoursesSlugRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/portal/courses': typeof PortalCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admissions/apply': typeof AdmissionsApplyRoute
  '/admissions/status': typeof AdmissionsStatusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/quizzes': typeof PortalQuizzesRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/results': typeof PortalResultsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/updates/academic': typeof UpdatesAcademicRoute
  '/updates/official': typeof UpdatesOfficialRoute
  '/updates/teacher-jobs': typeof UpdatesTeacherJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/portal/courses/$slug': typeof PortalCoursesSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/portal/courses/': typeof PortalCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/assignments'
    | '/admin/contacts'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/students'
    | '/admissions/apply'
    | '/admissions/status'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/portal/assignments'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/quizzes'
    | '/portal/register'
    | '/portal/resources'
    | '/portal/results'
    | '/resources/$slug'
    | '/updates/academic'
    | '/updates/official'
    | '/updates/teacher-jobs'
    | '/admin/'
    | '/admissions/'
    | '/blog/'
    | '/courses/'
    | '/portal/'
    | '/resources/'
    | '/admin/courses/$id'
    | '/portal/courses/$slug'
    | '/admin/courses/'
    | '/portal/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/contact'
    | '/faq'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/assignments'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/students'
    | '/admissions/apply'
    | '/admissions/status'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/portal/assignments'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/quizzes'
    | '/portal/register'
    | '/portal/resources'
    | '/portal/results'
    | '/resources/$slug'
    | '/updates/academic'
    | '/updates/official'
    | '/updates/teacher-jobs'
    | '/admin'
    | '/admissions'
    | '/blog'
    | '/courses'
    | '/portal'
    | '/resources'
    | '/admin/courses/$id'
    | '/portal/courses/$slug'
    | '/admin/courses'
    | '/portal/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/assignments'
    | '/admin/contacts'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/students'
    | '/admissions/apply'
    | '/admissions/status'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/portal/assignments'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/quizzes'
    | '/portal/register'
    | '/portal/resources'
    | '/portal/results'
    | '/resources/$slug'
    | '/updates/academic'
    | '/updates/official'
    | '/updates/teacher-jobs'
    | '/admin/'
    | '/admissions/'
    | '/blog/'
    | '/courses/'
    | '/portal/'
    | '/resources/'
    | '/admin/courses/$id'
    | '/portal/courses/$slug'
    | '/admin/courses/'
    | '/portal/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  AdmissionsApplyRoute: typeof AdmissionsApplyRoute
  AdmissionsStatusRoute: typeof AdmissionsStatusRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  PortalAssignmentsRoute: typeof PortalAssignmentsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalQuizzesRoute: typeof PortalQuizzesRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalResourcesRoute: typeof PortalResourcesRoute
  PortalResultsRoute: typeof PortalResultsRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  UpdatesAcademicRoute: typeof UpdatesAcademicRoute
  UpdatesOfficialRoute: typeof UpdatesOfficialRoute
  UpdatesTeacherJobsRoute: typeof UpdatesTeacherJobsRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  PortalCoursesSlugRoute: typeof PortalCoursesSlugRoute
  PortalCoursesIndexRoute: typeof PortalCoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/apply': {
      id: '/admissions/apply'
      path: '/admissions/apply'
      fullPath: '/admissions/apply'
      preLoaderRoute: typeof AdmissionsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/status': {
      id: '/admissions/status'
      path: '/admissions/status'
      fullPath: '/admissions/status'
      preLoaderRoute: typeof AdmissionsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/assignments': {
      id: '/portal/assignments'
      path: '/portal/assignments'
      fullPath: '/portal/assignments'
      preLoaderRoute: typeof PortalAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/quizzes': {
      id: '/portal/quizzes'
      path: '/portal/quizzes'
      fullPath: '/portal/quizzes'
      preLoaderRoute: typeof PortalQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/register': {
      id: '/portal/register'
      path: '/portal/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/resources': {
      id: '/portal/resources'
      path: '/portal/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof PortalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/results': {
      id: '/portal/results'
      path: '/portal/results'
      fullPath: '/portal/results'
      preLoaderRoute: typeof PortalResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/academic': {
      id: '/updates/academic'
      path: '/updates/academic'
      fullPath: '/updates/academic'
      preLoaderRoute: typeof UpdatesAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/official': {
      id: '/updates/official'
      path: '/updates/official'
      fullPath: '/updates/official'
      preLoaderRoute: typeof UpdatesOfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/teacher-jobs': {
      id: '/updates/teacher-jobs'
      path: '/updates/teacher-jobs'
      fullPath: '/updates/teacher-jobs'
      preLoaderRoute: typeof UpdatesTeacherJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/portal/courses/': {
      id: '/portal/courses/'
      path: '/portal/courses'
      fullPath: '/portal/courses/'
      preLoaderRoute: typeof PortalCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/courses/$slug': {
      id: '/portal/courses/$slug'
      path: '/portal/courses/$slug'
      fullPath: '/portal/courses/$slug'
      preLoaderRoute: typeof PortalCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  AdmissionsApplyRoute: AdmissionsApplyRoute,
  AdmissionsStatusRoute: AdmissionsStatusRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  PortalAssignmentsRoute: PortalAssignmentsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalQuizzesRoute: PortalQuizzesRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalResourcesRoute: PortalResourcesRoute,
  PortalResultsRoute: PortalResultsRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  UpdatesAcademicRoute: UpdatesAcademicRoute,
  UpdatesOfficialRoute: UpdatesOfficialRoute,
  UpdatesTeacherJobsRoute: UpdatesTeacherJobsRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  PortalCoursesSlugRoute: PortalCoursesSlugRoute,
  PortalCoursesIndexRoute: PortalCoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
